[theme]
primaryColor = "#00FF00"
backgroundColor = "#000000"
secondaryBackgroundColor = "#050505"
textColor = "#FFFFFF"
font = "monospace"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
